[package]
name = "compilers"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.dev]
panic = "abort"
opt-level = 0
lto = "off"
incremental = false

[profile.release]
strip = "symbols"
panic = "abort"
